name: 'qurious_cafe'
version: '1.0.0'
config-version: 2

profile: 'qurious_cafe'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  qurious_cafe:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
